ERROR: 2020-12-23 15:28:08,672: Traceback (most recent call last):
  File "/Users/acagliano/titrek-server-dev/titrek-server/core/trek_server.py", line 29, in __init__
    if self.config.ssl:
AttributeError: 'Config' object has no attribute 'ssl'

ERROR: 2020-12-23 15:30:47,475: Traceback (most recent call last):
  File "/Users/acagliano/titrek-server-dev/titrek-server/core/trek_server.py", line 29, in __init__
    if self.config.ssl:
AttributeError: 'Config' object has no attribute 'ssl'

ERROR: 2020-12-23 15:30:47,502: Traceback (most recent call last):
  File "/Users/acagliano/titrek-server-dev/titrek-server/core/trek_server.py", line 80, in run
    self.writeinfo()
  File "/Users/acagliano/titrek-server-dev/titrek-server/core/trek_server.py", line 236, in writeinfo
    "numclients":len(self.clients),
AttributeError: 'Server' object has no attribute 'clients'

